### ISSUE TITLE
Division by zero in LogFileSizeInfoBox.php line 62

### ISSUE THREAD

**Issue by georgringer** [froemken/mysqlreport#39]
in `$sizeOfEachLogFile = (int)($bytesWrittenEachHour / $variables['innodb_log_files_in_group']);`

**Comment by froemken** [comment]
Hi Georg,

each DB is a little bit different and contains different status values and variables. I have opened each Infobox file and added a lot of conditions if there is a division in that file. I have updated nearly 10 files. Hopefully I found all.

I have just uploaded version 1.1.3 to TER and Packagist which solves this issue.

Thank you for your report

Stefan
