### ISSUE TITLE
Improve rendering of slow queries

### ISSUE THREAD

**Issue by georgringer** [froemken/mysqlreport#45]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/1905663/200953649-12b1c99d-e036-4ca2-8081-bec4bfffe1b4.png">

proposal:
- render table header only if records found
- show info box if no queries found and reason: no logging, no slow queries?

**Comment by froemken** [comment]
Hi Georg,

I have added an infobox to this view and added such infoboxes also to Queries with FTS and filesort.

Thank you for your help

Stefan
