### ISSUE TITLE
use a sql formatter

### ISSUE THREAD

**Issue by georgringer** [froemken/mysqlreport#47]
what about using e.g. https://github.com/doctrine/sql-formatter to show the query in a improved way? would be fine for composer based only to avoid custom autoloading

**Comment by froemken** [comment]
Hi @georgringer 

good point. I have added a Service Locator with an optional SqlFormatter to a ViewHelper to solve that issue:

https://github.com/froemken/mysqlreport/blob/master/Classes/ViewHelper/Format/SqlViewHelper.php#L48

The change is already merged into master. Seems to be time for a 2.0.0 release. Yes, I have migrated the array syntax to Service.yaml. Damn...was hard work :-)

Nice greetings

Stefan
