### ISSUE TITLE
Incompatible queries with mysql only-full-group-by

### ISSUE THREAD

**Issue by liayn** [froemken/mysqlreport#78]
The methods `ProfileRepository::getProfileRecordsByUniqueIdentifier` and `ProfileRepository::findProfileRecordsForCall` use incomplete groupby statements.
Furthermore the `select` part omit proper quoting.

### For `getProfileRecordsByUniqueIdentifier`:

**Quoting:**
`->add('select', 'crdate, unique_call_identifier, mode, SUM(duration) as duration, COUNT(*) as amount')`
should be
```
->select('crdate', 'unique_call_identifier', 'mode')
->selectLiteral('SUM(duration) as duration', 'COUNT(*) as amount')
```

**GroupBy must be:**
`->groupBy('unique_call_identifier', 'crdate' , 'mode')`

### For `findProfileRecordsForCall`:

**Quoting:**
`->add('select', 'query_type, unique_call_identifier, SUM(duration) as duration, COUNT(*) as amount')`
should be
```
->select('query_type', 'unique_call_identifier')
->selectLiteral('SUM(duration) as duration', 'COUNT(*) as amount')
```

**GroupBy must be:**
`->groupBy('query_type', 'unique_call_identifier')`

**Comment by froemken** [comment]
Hi Markus,

can you please execute `SHOW GLOBAL VARIABLES;` and then post the value of `sql_mode` here?

Thank you

Stefan

**Comment by froemken** [comment]
Can you please add your database type and version?

**Comment by froemken** [comment]
I have solved that issue. New release available at packagist and TER.

Thank you for your help

Stefan

**Comment by liayn** [comment]
Thanks, I'll give it a shot soon.

**Comment by froemken** [comment]
PS: Using `select` and `selectLiteral` for one query is not possible, as the last one will always overwrite all columns of the previous select ;-) That's why I have used `add()` again for `selectLiteral` with the additional parameter for overwrite set to false.

**Comment by liayn** [comment]
> PS: Using `select` and `selectLiteral` for one query is not possible, as the last one will always overwrite all columns of the previous select ;-) That's why I have used `add()` again for `selectLiteral` with the additional parameter for overwrite set to false.

That's why there is `addSelectLiteral` ;-)
